language: objective-c
osx_image: xcode7
script:
    - pod install
    - set -o pipefail
    - xctool -workspace Example/EasySpotlight.xcworkspace -scheme EasySpotlight-Example -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
    - pod lib lint
